<?php

namespace Test\MyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{

    public function GetStateName($countryid)
    {
        $query = $this->getEntityManager()->createQuery('
        SELECT
            State
        FROM
            TestMyBundle:State State
        WHERE
            State.countryId =:countryid

        ORDER BY
            State.state ASC')
            ->setParameter('countryid',$countryid)
            ->getResult();
        return $query;
    }

    public function GetCityName($stateId)
    {
        $query = $this->getEntityManager()->createQuery('
        SELECT
            City
        FROM
            TestMyBundle:City City
        WHERE
            City.stateId =: stateId
        ORDER BY
            City.city ASC')
            ->setParameter('stateId', $stateId)
            ->getResult();

        return $query;
    }

    public function GetCityAreaName($cityId){

        $query = $this->getEntityManager()->createQuery('
         SELECT
            CityArea
        FROM
            TestMyBundle:CityArea CityArea
        WHERE
            CityArea.cityId =: cityId
        ORDER BY
            CityArea.cityArea ASC')
            ->setParameter('cityId', $cityId)
            ->getResult();
        return $query;
    }
}
