<?php

namespace Test\MyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{

    public function GetStateName($countryId)
    {
        $query = $this->getEntityManager()->createQuery('
        SELECT
            State
        FROM
            TestMyBundle:State
        WHERE
            State.countryId =: countryId
        ORDER BY
            State.state ASC')
            ->setParameter('countryId', $countryId)
            ->getResult();
        return $query;

    }

    public function GetCityName($stateId)
    {
        $query = $this->getEntityManager()->createQuery('
        SELECT
            City
        FROM
            TestMyBundle:City
        WHERE
            City.stateId =: stateId
        ORDER BY
            City.state ASC')
            ->setParameter('stateId', $stateId)
            ->getResult();

        return $query;
    }

    public function GetCityAreaName($cityId){

        $query = $this->getEntityManager()->createQuery('
         SELECT
            CityArea
        FROM
            TestMyBundle:CityArea
        WHERE
            CityArea.cityId =: cityId
        ORDER BY
            CityArea.cityId ASC')
            ->setParameter('cityId', $cityId)
            ->getResult();
        return $query;
    }
}
